name: code testing

on:
  pull_request:
    branches:
      - diff
  push:
    branches:
      - diff

env:
  RUSTFLAGS: "-Dwarnings"

permissions:
  pull-requests: write

jobs:
  should-succeed:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: jdrouet/action-git-identity@main
      - uses: jdrouet/action-git-metrics@install
      - uses: jdrouet/action-git-metrics@execute
        with:
          pull: "true"
          script: "add fake 10.0"
      - uses: "./"
        with:
          comment_tag: "git-metrics-check-success"
